### ISSUE TITLE
Rock Flavor

### ISSUE THREAD

**Issue by saarnold** [Brazilian-Institute-of-Robotics/bir.flat_fish-buildconf#1]
I'd like to integrate/move the Flatfish related packages, configurations and scripts from the DFKI internal gits into the BIR gits.
Are there currently any requirements e.g ruby version or rock flavor for this buildconf of flatfish?
If possible I would recommend to use the current release.

**Comment by doudou** [comment]
We use master because of the gazebo stuff and bugfixes in orocos.rb/syskit/vizkit
